### ISSUE TITLE
energy_mix and el_power_level

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#10]
Hi Daniel! The following from the readme about `el_power_level` and the value `electricity` for `energy_mix` only applies to the Truma Combi E (with 230V electricity supply), right?

> `energy_mix` and `el_power_level` should be set together.
> `energy_mix` can be one of `none`/`gas`/`electricity`/`mix`
>
> `el_power_level` can be set to `0`/`900`/`1800` when electric heating or mix is enabled

I have the non-E Combi 6, i.e. can only use gas for heating (water and air).

**Comment by danielfett** [comment]
Yes, you don't need to touch these values unless you have an E-version. I'll add a clarification in the readme.
