### ISSUE TITLE
Add Ground Connection to Truma RJ12

### ISSUE THREAD

**Issue by morawekj** [danielfett/inetbox.py#14]
Add Ground Connection to RJ12 Picture.
There is not Allways a Ground Connection from the PI to the Caravan DC

**Comment by danielfett** [comment]
Masse *gegen* etwas macht nicht so viel Sinn. Die Masseanschlüssen an deinem Pi (an den Pins, am Automation Hat, die USB-Buchse, etc.) sind alle miteinander verbunden und auf dem gleichen Potential. Wenn man einen DC-DC-Stepdown für den Pi nimmt, ist die Masse des Pis üblicherweise auch auf dem Potential derjenigen der Aufbauelektrik. Wenn du ein Steckernetzteil nimmst und das (wie üblich) einen zweipoligen Stecker hat, dann sollte das "floating" sein, d.h., es gibt keine Verbindung zur Masse des Fahrzeugs. Das würde auch genau dein Problem erklären. Du **musst** dann die Massen wie in der Anleitung miteinander verbinden, damit eine saubere Kommunikation möglich ist.

Dieses Video erklärt zumindest die Massen bei Steckernetzteilen gut: https://www.youtube.com/watch?v=xaELqAo4kkQ

Da das Problem hier behoben ist, mache ich zu.
