### ISSUE TITLE
ESP32 NodeMCU?

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#15]
Hello!

If this great project could be transposed to ESP32, would it matter if it's with CH340 or CP2102 USB-UART chip?

You get 3 of the latter for under 20€. Maybe that's the only advantage?

Apart from this, is it worth the trouble at all, since it should work on e.g. a Raspberry Pi 4?

Sorry, I know that this is not an "issue" but would not know where else to ask this question.

**Comment by danielfett** [comment]
I'm not going to implement this on an ESP32 (but might do so on a Pi Pico W). If anyone else wants to do that, that would be fine for me. 

The USB-UART chip does not matter as it will not be used.
