### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#18]
Hi Daniel,

Anbei ein kleiner (nicht wichtiger) Hinweis - in der README steht:

![Updating](https://user-images.githubusercontent.com/65889763/195665392-f082acfc-c8fe-473e-9781-750a1c28b864.png)

Das **```bash** gehört m.E. nicht dorthin. Und evtl. wolltest Du **as root** in Fett schreiben (zumindest bei mir erscheint es aber wie oben gezeigt - vermutlich auch ein GitHub Editor-Problem).

**Comment by danielfett** [comment]
Danke, ist behoben!
