### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#19]
Hier möchte ich gerne ein paar Debugging-Outputs liefern.

`pi@pi4:~ $ DEBUG_LIN=1 truma_service`

`pi@pi4:~ $ DEBUG_PROTOCOL=1 truma_service`

`pi@pi4:~ $ DEBUG_APP=1 truma_service`

Heute Abend schaffe ich es leider nicht mehr, weil ich den Output aus der ConnectBot App auf meinem Handy nicht vernünftig kopieren kann.

Gibt's evtl. die Möglichkeit, den Debugging-Ouput direkt und ausschließlich in eine Log-Datei umzuleiten und diese dann hier anzufügen?

`DEBUG_LIN=1 truma_service > lin.log` erzeugt eine leere Datei. Vermutlich mache ich es falsch oder es geht nicht.

Wie lange soll der Debug laufen?

Sollte ich während der Debug läuft, am CP+ etwas verändern (z.B. die Lüfterstufe)? Auch das kann ich erst morgen machen.

**Comment by danielfett** [comment]
`DEBUG_LIN=1 DEBUG_PROTOCOL=1 DEBUG_APP=1 truma_service > lin.log 2>&1` sollte es tun.

**Comment by danielfett** [comment]
Nö, da sollte nichts drin sein.

**Comment by mc0110** [comment]
Super, danke für Deine Mühe. Ich habe aber zwei Fragen:
1) Ich sehe keine "out <" Zeilen 
2) Ich sehe auch keine NAD=0x03 Nachrichten

**Comment by mc0110** [comment]
Hi, das war keine Kritik an Dir oder Deiner Mühe - mich wundert es nur, weil ich das in _send_answer als log-Eintrag gesehen habe. Die Frage geht also an Daniel.

BG Magnus

**Comment by danielfett** [comment]
Die Beobachtungen von Magnus teile ich - da fehlen Nachrichten. Die Kommunikation sieht so aus, als ob gar keine inetbox da wäre. Es gibt auch keine unbeantworteten Nachrichten. Daher gehe ich davon aus, dass während der Initialisierung schon was schief gegangen ist. 

Kannst du bitte mal ein Logfile des Init-Vorgangs machen?

Und danach: Schau mal im Settings-Menü der CP Plus nach, wenn du dort auf "Index" gehst und dann das Rad drehst - welche Versionsnummern kommen da (bitte alle auflisten).

**Comment by danielfett** [comment]
Die kommen vom CP Plus, das ist aber ein separates Set von Nachrichten, die vermutlich nicht originär für die iNet-Box bestimmt sind. Auf jeden Fall kann man damit keine Einstellungen vornehmen.

**Comment by mc0110** [comment]
Hi,
sorry für meine Abkürzung - die NAD ist die node address. Ja, die 0x03 taucht auf, die Init-Meldung ist auch im LOG. Sieht sehr gut aus. Es müsste jetzt auch das Einstellen funktionieren. Vielleicht versuchst Du mal, etwas zu ändern.
Also jetzt nochmals Glückwunsch!

**Comment by mc0110** [comment]
Hallo zusammen,

@7wells : Im Index müsste nach der Aktivierung der iNetbox ein dritter Eintrag kommen.

Kurzes Update von meiner eigenen TRUMA: Dank der tollen Beschreibung klappt der LIN-Anschluss mit einem Adapter gut, nachdem ich festgestellt habe, dass im [Adapter](https://www.amazon.de/gp/product/B00173AL3K/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) die Anschlüsse links und rechts getauscht sind - also Pin 1-6, 2-5, 3-4. Mit einer sauberen Masseverbindung braucht man nur das LIN-Signal (also in Daniels Abbildung den grünen Pin und daher reicht auch eine RJ11-Verbindung).

Damit konnte ich die LIN-Frames der CPplus / TRUMA mit einem UART-TCP-Server sehr gut sehen und auch die Checksum verifizieren, allerdings wollte der aufgesetzte RPI3 sich nicht auf die 0x00/0x55-Blöcke synchronisieren und der Log zeigte nur "Datenmüll". Um es kurz zu machen: Es gibt wohl auf dem UART (Besonderheit beim RPI3) ein Timing-Problem bei den neueren Softwareversionen. Abhilfe schaffte der Hinweis von [Prof. Plate](http://www.netzmafia.de/skripten/hardware/RasPi/RasPi_Serial.html). Nachdem ich das Bluetooth abgeschaltet hatte, kamen auch nach dem Rebooten die ersten korrekten Meldungen im truma_service Log.

Kleiner Hinweis noch zum INIT auf dem CPplus. Ich musste das INIT mehrfach anstossen, bis die ersehnte Meldung in den Logs kam. Im Debug-Mode ist es leicht zu erkennen, denn erst mit der Initialisierung fängt der RPI3 an zu antworten. Es gibt also mit DEBUG_LIN=1 danach erst "out >" Meldungen, aber diese auch sehr regelmässig.

Danach lässt dich die TRUMA steuern - echt toll und Danke an @danielfett und alle anderen, die daran beteiligt gewesen sind. Eine echt tolle Erweiterung des smarten RV.

**Comment by mc0110** [comment]
@7wells 
T23.70.0 

Der Eintrag ist erst nach der Initialisierung des Inet-Simulators aufgetaucht. Ich vermute C steht für die Version des CPPlus, H für die Version der TRUMA und T dann für die "Version", die die Box hätte.

Die out-Meldungen hattest Du auch erst nach der Initialisierung. Wegen Deiner Beschreibung habe ich es auch mehrfach versucht, das INIT zu machen. Erst beim 3. oder 4. Versuch hat die iNet-Box angefangen zu antworten.

Kannst Du denn jetzt die TRUMA steuern? Heizung an/aus Wasser an/aus hat gestern bei mir geklappt.

**Comment by mc0110** [comment]
In /boot/config.txt die Zeilen ergänzt:
core_freq=250
enable_uart=1
dtoverlay=pi3-miniuart-bt

und dann noch als sudo
sudo systemctl disable hciuart

Nach einem Reboot war das Timing dann okay und die Syncs (0x00, 0x55) funktionierten.

**Comment by danielfett** [comment]
Man könnte es in der Software abklemmen, aber das ist derzeit nicht eingebaut. Du könntest einfach RX am Pi trennen, dann solltest du alles zusammen betreiben können.

**Comment by skrebber** [comment]
Aber ich dachte, die Timing-Geschichte bezieht sich nur auf den miniUART. Und daher sollte man auch den PL011 nehmen, weil der viel stabileres timing hat, weil vom GPU-Takt unabhängige Hardware-Lösung. 
Wenn du über dtoverlay=disable-bt bluetooth ausschaltest, dann wird auf den GPIO pins der PL011 gelegt und es dürfte eigentlich nichts mit dem GPU-Takt zu tun haben.

Oder liege ich falsch?
