### ISSUE TITLE
README: Changing settings

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#20]
Hi Daniel, im README schreibst Du:
> **Changing settings**
> 
> In general, publish a message to `service/truma/set/<setting>` (where `<setting>` is one of the settings published in `service/truma/control_status/#)` with the value you want to set. After restarting the service, wait a minute or so until the first set of values has been published before changing settings.

Du meinst damit nicht, dass nach jeder Änderung eines Werts mittels `mosquitto_pub` der Service neu gestartet werden muss, aber so könnte man es aufgrund der Satzstellung missverstehen.

Wäre es so evtl. deutlicher?
> **Changing settings**
> 
> In general, before you change a setting, restart the service (`sudo systemctl restart miqro_truma`) and wait a minute or so until the first set of values has been published. Then publish a message to `service/truma/set/<setting>` (where `<setting>` is one of the settings published in `service/truma/control_status/#)` with the value you want to set.

**Comment by danielfett** [comment]
PR #21 gemerged, dankeschön!
