### ISSUE TITLE
Caveat about Truma update?

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#25]
@danielfett @morawekj
I opened the Truma app the first time after a longer while not using it and received a message about an available update. It reads (in German):

> INET BOX UPDATE VERFÜGBAR
> Bitte laden Sie das Update innerhalb der nächsten 30 Tage auf alle Endgeräte sowie Ihre Truma iNet Box, um die Funktionen Ihres Systems auch weiterhin sicherzustellen.
> OK

It reminds of other IoT gadgets that receive vendors' updates that are not always to the best of the customers. Regarding the **inetbox.py project**, I wonder if the vendor could change the workings of the Truma communication protocol (incl. encryption, maybe?) that could render this nice project useless.

Do you or anybody else knowledgeable of the protocol etc. have a clue if this could happen?

I assume that as long as no iNet box is connected and used, no undesired update can happen. Maybe people who do use the iNet box, might face problems with remote control (sending/receiving SMS), if not updating the software/firmware.

Thanks for sharing your thoughts!

**Comment by dougle03** [comment]
In theory, yes it could happen. But Truma would need a good reason to make such wholesale changes, generally these changes are profit driven, so unless there is a good profit reason to spend substantial developer/tester time to make big changes, then I suspect it would be unlikely that an update would cause significant upset.
Of course, the more popular this hack becomes, then that might convince Truma to make changes, but I doubt that day will come any time soon. As far as I can tell, Truma are moving away from independent hvac control, and more towards integration with a vehicle manufacturers integrated vehicle control systems. This is already happening with some UK manufactured vehicles where the CP panel has gone and the vehicles main systems panel has taken over being the interface for the boiler/AC systems. 
Given this, making changes to the bus protocol would cause integration partner problems, so even less likely they would make wholesale changes.
