### ISSUE TITLE
LIN to UART Transceiver

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#4]
Hi Daniel!

First of all, I would like to congratulate and thank you very much for your efforts and great results on this topic. 👍

I have a hardware-related question and hope that you don't mind me putting it here under "Issues":
You mention the MEROURII bus module as LIN to UART Transceiver. I own this LIN-Bus Breakout Board:
https://buyzero.de/products/lin-bus-breakout-board
I wonder if that can serve the same purpose?

The main differences I see on the first glance is that the SK Pang electronics board has a 3.3 V or 5 V supply, a jumper to toggle master/slave (would that be needed for our use case at all?), but lacks the comfortable screw terminal. Your board can directly use the 12 V from the heating, whereas mine needs a DC/DC down-stepper. I have [this one](https://www.amazon.de/gp/product/B07NLV411C) (seems to be the same as in your slides), which I will use for the RPi power supply anyway.

Cheers
7wells

**Comment by danielfett** [comment]
Thank you!
I'm not sure how the TJA1020 and the MCP2004 compare. In any case, I guess it should not be too hard to adapt the software in case any adaptions are needed. If you have the board already, you can just try if the software works...

**Comment by mc0110** [comment]
Hi Daniel,

it's great that you have breathed with your solution new life into the WomoLIN-project. I am totally enthusiastic about your solution - I have been looking for something comparable for the Truma in my RV for a long time. 
Even though your solution is very elegant, I would want to implement it on an ESPHOME basis for convenience, because I have a HOME ASSISTANT instance running in the RV with several ESP32s, but without an MQTT server. From your code I found the abstractions in the LIN module and your MQTT lib MIQRO. What I have not yet found in your code is a listing of the commands / data imports. That would be very helpful to realise the CustomSensors in ESPHOME. 
But don't get me wrong, please. It's a really great project and fantastic work. Thanks for that!

**Comment by danielfett** [comment]
Hi Magnus,
I'm not sure I understand your use case - isn't ESPHOME also MQTT-based?

Unfortunately, getting data from the control unit and sending commands is not as easy as parsing or answering specific message. You will need to implement parts of the LIN Transport Layer unless you just want to read status messages from the bus. To sum up what you need to do: 

 - You need to answer messages with PID 0x18 - the first bit defines whether you want to send a command to the control unit or not. See https://github.com/danielfett/inetbox.py/blob/master/inetbox/inetbox.py#L135
 - If you want to read status messages, you need to interprete LIN messages with PIDs 0x20-0x22, see https://github.com/danielfett/inetbox.py/blob/master/inetbox/inetbox.py#L397-L459
 - And then you also need to implement at least parts of the LIN Transport layer. Please see the LIN specification for details on this layer. The low-level communication is based on the messages with PIDs 0x3C and 0x3D. On the transport layer, you need to send specific answers to certain messages, as implemented here https://github.com/danielfett/inetbox.py/blob/master/inetbox/inetbox.py#L24-L87
 
The SID 0xBB indicates a data download, 0xBA indicates a request for data upload. Using these messages, a buffer is sent back and forth between the control unit and inetbox.py. The buffer can be of different types, each to be interpreted differently. Four types are currently defined in inetbox.py, these are defined here: https://github.com/danielfett/inetbox.py/blob/master/inetbox/inetbox.py#L233-L318

Regarding the module I'm using, it does not need a level shifter. It works with 3.3 and 5V.

**Comment by mc0110** [comment]
Hi Daniel,
thank you for the detailed answer. I have already seen in the first analysis that the communication is not quite simple, even though you have structured it really excellently.

I attach the link to the internal API on TCP basis, as ESPHOME uses it for communication. The direct comparison to MQTT is also discussed there [https://esphome.io/components/api.html](https://esphome.io/components/api.html).

I think I will try to get your solution working in a first step and only try to implement the transport layer on the ESP platform in a second step.

**Comment by mc0110** [comment]
In Deinem Code ist ein read_log.py. Darin hast Du die Option, auch ein File einzulesen. Könntest Du dazu noch ein Beispiel-File zur Verfügung stellen. Das würde mir riesig helfen.

**Comment by danielfett** [comment]
@mc0110 Can you please file a separate Issue per topic? Thank you!

**Comment by mc0110** [comment]
that's right, I will

**Comment by danielfett** [comment]
Since it doesn't seem that there's an open question here, I'll close this issue. Feel free to add new ones if new questions come up!
