### ISSUE TITLE
mqtt auth

### ISSUE THREAD

**Issue by skrebber** [danielfett/inetbox.py#5]
Hi Daniel,
I wanted to try your software out, but I have not yet figured out how to set username and password for authentication of the mqtt broker. Can you give me a hint?

Thanks in advance,
best regards,
Sönke

**Comment by danielfett** [comment]
Hi Sönke,

I added authentication and TLS settings to the MIQRO framework. After updating MIQRO to V1.2.0 (`pip3 install --upgrade miqro`) you can set the username and password as described here: https://github.com/danielfett/miqro#authentication-and-tls
