### ISSUE TITLE
LIN on RJ12 and GND/12V+ source? Pimoroni Automation HAT?

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#7]
Hi Daniel!

Sorry that I have these dumb questions:

Is LIN (the only of the 6 lines you have highlighted on the RJ12 connector) really the only line that gets connected with the Truma Combi?

GND and 12V+ on the transceiver do not have to come from the Truma but could also come from another source that is not toggled?

I do not yet quite understand what is connected where. :blush:

And how do you connect PINs 14 and 15 of your Raspberry Pi if it has the Pimoroni Automation HAT attached, or don't you use it anymore?

Thanks for your time and help!

**Comment by danielfett** [comment]
Yes, LIN is the only line that is used from the RJ12 connector. GND and 12V can come from any other source. I use the same source that powers the Raspberry Pi (before conversion to 5V, obviously).

Pins 14 & 15 are directly available on the screw terminals of the Automation HAT.

**Comment by danielfett** [comment]
I'm using Raspberry Pi OS. But since the pins on Automation HAT are directly connected to Pins 14 and 15 on the Pi, it does not matter whether you have the Automation HAT software installed or not. You don't need it for this software package to work.

The marked pins are the correct ones.

**Comment by skrebber** [comment]
@7wells : you mentioned that you used AppDaemon for Homeassistant. At the moment I'm using a separate pi because of the inconvenience of the supervised install method. Can you share your AppDaemon config? How do you install packages with pip in the AppDaemon sandbox? Thx!
