### ISSUE TITLE
Cannot start truma miqro service

### ISSUE THREAD

**Issue by 7wells** [danielfett/inetbox.py#8]
Hi Daniel, I followed your installation guide, i.e. first installed as normal user. It further reads: "After you have tested that the software works for you". Erm, how can I test it? 😊

BTW, I put this in my .bashrc: `export PATH="$HOME/.local/bin:$PATH"`

Then I installed everything as admin (with sudo) but got this error message after trying to start this service:
```
pi@pi4:~ $ sudo systemctl status miqro_truma
● miqro_truma.service - truma MIQRO microservice
     Loaded: loaded (/etc/systemd/system/miqro_truma.service; disabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-10-04 18:53:39 CEST; 12s ago
    Process: 3095 ExecStart=/usr/bin/env python3 /usr/local/bin/truma_service (code=exited, status=1/FAILURE)
   Main PID: 3095 (code=exited, status=1/FAILURE)
        CPU: 336ms
```
Can you please point me to a direction where I should have a closer look? Thank you!

**Comment by danielfett** [comment]
Please check the log files using `journalctl -xf -u miqro_truma.service`. Any errors there?

**Comment by danielfett** [comment]
Seems that you need to create the config file as per the README.

Yes, testing as a normal user is easier. It is important, however, that you don't do both (running the service twice will lead to errors).

**Comment by danielfett** [comment]
You can just run `truma_service` from the command line. Note that `pip3 uninstall` will remove both the service and the executable, so `sudo service miqro_truma stop` might be the better option to stop the service.

Yes, you need some mqtt broker running for that to work.

**Comment by danielfett** [comment]
Yes, looks good.

The hexadecimal number is a memory location, not particularly helpful here.

**Comment by danielfett** [comment]
It seems that the operation of the script interrupts the connection between CP Plus and the heater. Is everything connected correctly?

**Comment by danielfett** [comment]
The second LIN plug on the Combi should be fine. I wonder if there might be a short circuit between some of the lines.

**Comment by danielfett** [comment]
Two things:

 * Are you sure the yellow one is the correct one from the RJ12 cable? While the colors are not standardized, it was the green line for me.
 * How are RX and TX connected (which one is on GPIO #14 and #15, respectively)?

**Comment by danielfett** [comment]
> I will check the lines tomorrow with a multimeter. Would it be correct to unplug the CAN cable from the Truma Combi and then simply check all lines if they "go through"? (i.e. between the CAN cable from the Truma combi and the UART, the RPi, and the CP+)

There's not too much you can measure there. I rather suspect that something is not connected properly. Did you ensure that there is no short-circuit between any of the other lines coming from the RJ12?
